import { FaArrowLeft, FaArrowRight, FaArrowUp, FaArrowDown, FaPlus, FaMinus, FaBars, FaUser, 
    FaShoppingCart, FaSearch, FaHome, FaCog, FaStar, FaStarHalfAlt, FaRegStar, FaThumbsUp, FaThumbsDown,
    FaCheck, FaTimesCircle, FaTrash, FaInfo, FaQuestion, FaEnvelope, FaPhone } from 'react-icons/fa'; 

export const ICONS = {
    'FaArrowLeft': FaArrowLeft,
    'FaArrowRight': FaArrowRight,
    'FaArrowUp': FaArrowUp,
    'FaArrowDown': FaArrowDown,
    'FaPlus': FaPlus,
    'FaMinus': FaMinus,
    'FaBars': FaBars,
    'FaUser': FaUser,
    'FaShoppingCart': FaShoppingCart,
    'FaSearch': FaSearch,
    'FaHome': FaHome,
    'FaCog': FaCog,
    'FaStar': FaStar,
    'FaStarHalfAlt': FaStarHalfAlt,
    'FaRegStar': FaRegStar,
    'FaThumbsUp': FaThumbsUp,
    'FaThumbsDown': FaThumbsDown,
    'FaCheck': FaCheck,
    'FaTimesCircle': FaTimesCircle,
    'FaTrash': FaTrash,
    'FaInfo': FaInfo,
    'FaQuestion': FaQuestion,
    'FaEnvelope': FaEnvelope,
    'FaPhone': FaPhone
}
